name: Docker test and publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    env:
      PUPPERWARE_ANALYTICS_STREAM: production
      IS_LATEST: true
      # Still need these env vars for README publishing

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Login do docker.io
        run: docker login -u abhishek138 -p abhishek138
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - run: gem install bundler
      - name: Build container
        working-directory: docker
        run: |
          docker system prune --all --force --volumes
          docker builder prune --force --keep-storage=10GB
          make lint build test
      - name: Publish container
        working-directory: docker
        run: |
          make publish
      - name: Build release container
        env:
          IS_RELEASE: true
        working-directory: docker
        run: |
          if make prep; then
            make lint build test
          else
            echo "Skipping release container building and testing"
          fi
      - name: Publish release container
        env:
          IS_RELEASE: true
        working-directory: docker
        run: |
          if make prep; then
            make publish
          else
            echo "Skipping release container publishing"
          fi

